[workspace]
members = [
  "rbe01",
  "rbe01-1",
  "rbe01-2",
  "rbe01-2-1",
  "rbe01-2-2",
  "rbe01-2-2-1",
  "rbe01-2-3",
  "rbe02",
  "rbe02-1",
  "rbe02-2",
  "rbe02-3",
  "rbe03-1",
  "rbe03-2",
  "rbe03-3",
  "rbe04",
  "rbe04-1",
  "rbe04-2",
  "rbe04-3",
  "rbe04-4",
  "rbe05-1",
  "rbe05-2",
  "rbe05-3",
  "rbe05-4",
  "rbe06-1",
  "rbe06-2",
  "rbe06-3",
  "rbe07",
  "rbe08-1",
  "rbe08-2",
  "rbe08-2-1",
  "rbe08-2-2",
  "rbe08-3",
  "rbe08-4",
  "rbe08-5",
  "rbe08-5-1-1",
  "rbe08-5-1-2",
  "rbe08-5-1-3",
  "rbe08-5-1-4",
  "rbe08-5-2",
  "rbe08-5-3",
  "rbe08-6",
  "rbe08-7",
]
