[workspace]
members = [
  "rbe01",
  "rbe01-1",
  "rbe01-2",
  "rbe01-2-1",
  "rbe01-2-2",
  "rbe01-2-2-1",
  "rbe01-2-3",
  "rbe02",
  "rbe02-1",
  "rbe02-2",
  "rbe02-3",
  "rbe03-1",
  "rbe03-2",
  "rbe03-3",
  "rbe04",
  "rbe04-1",
  "rbe04-2",
  "rbe04-3",
  "rbe04-4",
]
